>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

>>> print(lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]]))
[[ 7 10]
 [15 22]]

>>> print(lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]]))
[[13 16]]

>>> print(lazy_matrix_mul([[1,2]],"string"))
Traceback (most recent call last):
    ...
numpy.core._exceptions._UFuncNoLoopError: ufunc 'matmul' did not contain a loop with signature matching types (dtype('int64'), dtype('<U6')) -> None

>>> print(lazy_matrix_mul([],[[1,2]]))
Traceback (most recent call last):
    ...
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 0)

>>> print(lazy_matrix_mul([[1,2]],[]))
Traceback (most recent call last):
    ...
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 0 is different from 2)

>>> print(lazy_matrix_mul([['a','b']],[[1,2]]))
Traceback (most recent call last):
    ...
numpy.core._exceptions._UFuncNoLoopError: ufunc 'matmul' did not contain a loop with signature matching types (dtype('<U1'), dtype('int64')) -> None

>>> print(lazy_matrix_mul([[1,2]],[['a','b']]))
Traceback (most recent call last):
    ...
numpy.core._exceptions._UFuncNoLoopError: ufunc 'matmul' did not contain a loop with signature matching types (dtype('int64'), dtype('<U1')) -> None

>>> print(lazy_matrix_mul([[1,2,3]]))
Traceback (most recent call last):
    ...
TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

>>> print(lazy_matrix_mul())
Traceback (most recent call last):
    ...
TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'

>>> print(lazy_matrix_mul([[1,2,3]],[[1,2,3],[1,2,3]]))
Traceback (most recent call last):
    ...
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

>>> print(lazy_matrix_mul([[1,2]],[[1,2],[1]]))
Traceback (most recent call last):
    ...
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

>>> print(lazy_matrix_mul([[1,2],[1]],[[1,2]]))
Traceback (most recent call last):
    ...
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
